version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    env_file:
      - .env/development/database
      - .env/development/web
    depends_on:
      - database
      - webpack
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack

  webpack:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/app
    env_file:
      - .env/development/web
      - .env/development/database
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  database:
    image: docker.io/postgres:14.2
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: docker.io/redis:7.0.0

volumes:
  db_data:
  gem_cache:
  node_modules:
