version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    env_file:
      - .env/development/database
      - .env/development/web
    depends_on:
      - database
      - webpack

  webpack:
    build: .
    command: bash -c "./bin/webpack-dev-server"
    ports:
      - 3035:3035
    volumes:
      - node_modules:/app/node_modules
    env_file:
      - .env/development/web
      - .env/development/database
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  database:
    image: postgres:13
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6

volumes:
  db_data:
  gem_cache:
  node_modules:
